version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_tracker
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5434:5432"

#  mongo:
#    image: mongo:latest
#    volumes:
#      - ./data/mongo:/data/db
#    ports:
#      - "27017:27017"
#
#  zookeeper:
#    image: wurstmeister/zookeeper:latest
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: wurstmeister/kafka:latest
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper

  dispatcher:
    build: ./dispatcher
    ports:
      - "8080:8080"
#    depends_on:
#      - kafka

  server:
    build: ./server
    ports:
      - "8081:8081"
    depends_on:
#      - kafka
      - postgres
#      - mongo

volumes:
  postgresql: